# Generated by Django 4.1.4 on 2022-12-25 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(blank=True, max_length=200, null=True)),
                ('kod', models.CharField(blank=True, max_length=200, null=True)),
                ('zobrazit', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnota', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnota_atributu_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.attributevalue')),
                ('nazev_atributu_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.attributename')),
            ],
        ),
    ]
